regions:
  - name: hangzhou-cluster-a
    nacos:
      url: http://hangzhou-cluster-a.nacos:8848/nacos/v1/ns/instance/list
      namespace_id: bbee192d-a3bb-490f-baca-293d33d9d923
    services:
      - service1 
      - service2
  - name: beijing-cluster-a
    nacos:
      url: http://beijing-cluster-a.nacos:8848/nacos/v1/ns/instance/list
      namespace_id: bbee192d-a3bb-490f-baca-293d33d9d923
    services:
      - service1 
      - service2
